### ISSUE TITLE
Update to lens 6.0.1

### ISSUE THREAD

**Issue by trombini77** [artturik/lens-extension-network-policy-viewer#3]
Does have any intention to update the extension to lens 6.0.1?
![image](https://user-images.githubusercontent.com/13336060/185696569-ac48916a-f0fd-4dd9-b1f3-e3691d0877e3.png)

**Comment by floviolleau** [comment]
Hi,

Use master : https://github.com/artturik/lens-extension-network-policy-viewer/archive/refs/heads/main.tar.gz

**Comment by artturik** [comment]
Hey, thanks for reporting.

I have added support of Lens ^6.0.0 in latest commit - https://github.com/artturik/lens-extension-network-policy-viewer/commit/3167418a8e717b8f92a481099af988ff3aa8084a

Please update an extension and it should work again!
